#!/bin/bash
#SBATCH -J mgelbr-BD
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36 #4x3x3
#SBATCH --cpus-per-task=1
#SBATCH -t 4-24:00:00
#SBATCH -p long
#SBATCH -o %A.out
#SBATCH -e %A.err

start=$SECONDS

module purge
module load miniconda3/24.11.1
module load OpenBLAS/0.3.29
module load OpenMPI/4.1.6
source /software/hoomd4.2.1-mod-rigidity/hoomdmod4.2.1-rigidity-venv/bin/activate 

mpirun python3 sim-gel-morsebrush-BD.py tag D0 kappa_m kappa_e Z_val L_elec r0_val hb_val m_K_val

time=$((SECONDS-start))
echo The simulation ran for $((time / 86400))day"(s)" $(((time / 3600) % 24))hr"(s)" $(((time / 60) % 60))min $((time % 60))sec real "(wall clock)" time >&1
