#!/bin/bash

# Redirect stdout and stderr to a file named with today's date
# (but use tee so that the output is also displayed on the terminal)
current_date=$(date +"%Y-%m-%d")
output_file="joblist_${current_date}.txt"
exec > >(tee -a "$output_file") 2>&1

pwd

D0=( '2' '4' '9' '14' '19' '28' '38' )
morse_tags=('0.5mgmL' '1mgmL' '2mgmL' '3mgmL' '4mgmL' '6mgmL' '8mgmL')

salts=( '2.5' '3.5' '5' '10' )
kappa_e=( '113' '134' '160' '226' )
L_elec_H=( '9.9' '10.1' '10.5' '11.1' )
L_elec_L=( '1.2' '1.2' '1.2' '1.2' )


# 'H' vs. 'L'
monomer=('H' 'L')
Z=('778' '359')
charges=( '33' '22' )
r0_values=( '12' '4' )
kappa_m=( '75' '75' )

# total potential (for K scaling)
U0_2_H=( '0.0' '0.0' '0.0' '0.1' '0.3' '0.9' '1.9' )
U0_3_H=( '0.0' '0.0' '0.2' '0.6' '1.1' '2.8' '4.9' )
U0_5_H=( '0.0' '0.1' '0.6' '1.4' '2.4' '5.0' '8.0' )
U0_10_H=( '0.2' '0.6' '1.8' '3.5' '5.3' '9.7' '14.1' )


U0_2_L=( '0.0' '0.0' '0.2' '0.8' '1.9' '5.4' '9.9' )
U0_3_L=( '0.0' '0.2' '0.9' '2.3' '4.2' '9.4' '15.1' )
U0_5_L=( '0.1' '0.5' '2.0' '4.3' '7.0' '13.5' '20.2' )
U0_10_L=( '0.6' '1.5' '4.6' '8.2' '12.0' '20.4' '28.3' )

# brush effects
K_scale=( '0' '1' ) 
hb_values=( '60' )

for ((p=0; p<${#Z[@]}; p++)); do
  monomer_val="${monomer[$p]}"
  Z_val="${Z[$p]}"
  charge_tag="${charges[$p]}mV"
  r0_val="${r0_values[$p]}"
  km_val="${kappa_m[$p]}"

  case "$monomer_val" in
    "H")
      declare -n L_elec=L_elec_H
      ;;
    "L")
      declare -n L_elec=L_elec_L
      ;;
    *)
      echo "Unknown monomer value: $monomer_val"
      continue
      ;;
  esac

  for ((h=0; h<${#hb_values[@]}; h++)); do
    hb_val="${hb_values[$h]}"
    km_val="${kappa_m[$h]}"

    for ((d=0; d<${#D0[@]}; d++)); do
      D0_val="${D0[$d]}"
      morse_tag="${morse_tags[$d]}"


      for ((s=0; s<${#salts[@]}; s++)); do
        kappa_e_val="${kappa_e[$s]}"
        salt_tag="${salts[$s]}mM"
        L_elec_val="${L_elec[$s]}"

        case "$salt_tag" in
          "2.5mM") declare -n U0="U0_2_${monomer_val}" ;;
          "3.5mM") declare -n U0="U0_3_${monomer_val}" ;;
          "5mM")   declare -n U0="U0_5_${monomer_val}" ;;
          "10mM")  declare -n U0="U0_10_${monomer_val}" ;;
          *) echo "Unknown salt value: $salt_tag"; continue ;;
        esac

        U0_val="${U0[$d]}"
        #echo $U0_val

	for ((ks=0; ks<${#K_scale[@]}; ks++)); do
          scale=${K_scale[ks]}
  	  K_val=$(printf "%.0f" "$(echo "$U0_val * $scale" | bc -l)")

          tag="${morse_tag}-${salt_tag}-K${K_val}_${monomer_val}"
          #echo $tag

          path="K_${scale}xUC/hb_${hb_val}nm-${monomer_val}/$morse_tag-$salt_tag-K${K_val}"
          file="../sim-scripts/potential-morsebrush/${path}/Gelation-${tag}-BD.gsd"

          # only run if the GSD file exists
          if [[ -f "$file" ]]; then
            echo $file
             sbatch analyze-batch-BD "$file" "$tag" "$hb_val" "$km_val"
            echo "---"
          fi

        done
        unset -n U0
      done
    done
  done
  unset -n L_elec
done
